"""added about_me and last_seen to users

Revision ID: 739bb866e7a0
Revises: 66dd94532593
Create Date: 2018-10-16 18:21:11.324909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739bb866e7a0'
down_revision = '66dd94532593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
